services:
  postgres_db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: quarkus
      POSTGRES_USER: quarkus
      POSTGRES_DB: quarkus
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sudo pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - whole_network

networks:
  whole_network:
    driver: bridge
